version: 2
updates:
- package-ecosystem: nuget
  directory: "/RHL Updater"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/ResourceHubLauncher"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
